/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class JFrameAdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAdminPanel
     */
    public JFrameAdminPanel() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private Admin admin;
    public JFrameAdminPanel(Admin admin) {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.admin = admin;
        jLabel2.setText(admin.getUserName());
        
        jTextField1.setText(admin.getUserName());
        jTextField3.setText(admin.getUserRealName());
        jTextField4.setText(admin.getUserContact());
        jTextField5.setText(admin.getAccountType());
        
        
             
        userTableInitialize(jTable1);
        this.registrationTableInitialize(jTableRegistration);
        //propertyTableInitialize(jTable3);
        propertyTableInitialize(jTablePropertyListing);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        Profile = new javax.swing.JTabbedPane();
        jPanelProfileTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanelRegistrationManagerTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegistration = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelUserManagerTab = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxPropertyType = new javax.swing.JComboBox<>();
        jComboBoxMinPrice = new javax.swing.JComboBox<>();
        jComboBoxProjectName = new javax.swing.JComboBox<>();
        jComboBoxMaxPrice = new javax.swing.JComboBox<>();
        jComboBoxCurrentStatus = new javax.swing.JComboBox<>();
        jComboBoxPriceSortingMethod = new javax.swing.JComboBox<>();
        jButtonSearch = new javax.swing.JButton();
        jCheckBoxSwimmingPool = new javax.swing.JCheckBox();
        jCheckBoxTV = new javax.swing.JCheckBox();
        jCheckBoxWifi = new javax.swing.JCheckBox();
        jCheckBoxAirConditioner = new javax.swing.JCheckBox();
        jCheckBoxFridge = new javax.swing.JCheckBox();
        jCheckBoxWaterHeater = new javax.swing.JCheckBox();
        jCheckBoxWashingMachine = new javax.swing.JCheckBox();
        jCheckBoxGymRoom = new javax.swing.JCheckBox();
        jCheckBoxBalcony = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePropertyListing = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPropertyID = new javax.swing.JTextField();
        jButtonGetPropertyDetail = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Currently logged in :");

        jLabel2.setText("username");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jLabel5.setText("Real name");

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Contact");

        jLabel7.setText("Role");

        jTextField5.setEditable(false);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProfileTabLayout = new javax.swing.GroupLayout(jPanelProfileTab);
        jPanelProfileTab.setLayout(jPanelProfileTabLayout);
        jPanelProfileTabLayout.setHorizontalGroup(
            jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfileTabLayout.createSequentialGroup()
                .addGroup(jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProfileTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProfileTabLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)))
                    .addGroup(jPanelProfileTabLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton1)
                        .addGap(79, 79, 79)
                        .addComponent(jButton6)))
                .addContainerGap(590, Short.MAX_VALUE))
        );
        jPanelProfileTabLayout.setVerticalGroup(
            jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfileTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addGroup(jPanelProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addGap(26, 26, 26))
        );

        Profile.addTab("Profile", jPanelProfileTab);

        jTableRegistration.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRegistration);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Approve/Deny");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelRegistrationManagerTabLayout = new javax.swing.GroupLayout(jPanelRegistrationManagerTab);
        jPanelRegistrationManagerTab.setLayout(jPanelRegistrationManagerTabLayout);
        jPanelRegistrationManagerTabLayout.setHorizontalGroup(
            jPanelRegistrationManagerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrationManagerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistrationManagerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelRegistrationManagerTabLayout.setVerticalGroup(
            jPanelRegistrationManagerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrationManagerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        Profile.addTab("Registration Manager", jPanelRegistrationManagerTab);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton11.setText("View");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Add");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Edit / Remove");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelUserManagerTabLayout = new javax.swing.GroupLayout(jPanelUserManagerTab);
        jPanelUserManagerTab.setLayout(jPanelUserManagerTabLayout);
        jPanelUserManagerTabLayout.setHorizontalGroup(
            jPanelUserManagerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserManagerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserManagerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelUserManagerTabLayout.setVerticalGroup(
            jPanelUserManagerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserManagerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Profile.addTab("User Manager", jPanelUserManagerTab);

        jTextFieldAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Search Address:");

        jComboBoxPropertyType.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxPropertyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Property Type", "Bungalow", "Semi-D", "Terrace/Link", "Townhouse", "Penthouse", "Condominium", "Duplex/Studio", "Apartment/Flat", "SoHo/SoVo/SoFo", "Mixed Development" }));
        jComboBoxPropertyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPropertyTypeActionPerformed(evt);
            }
        });

        jComboBoxMinPrice.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxMinPrice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Min Price (RM)", "500", "1000", "1500", "2000", "2500", "3000", "3500", "4000", "5000" }));

        jComboBoxProjectName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxProjectName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any Project", "Cyberia", "Third Avenue", "Solstice", "Eclipse Residence", "Cristal Serin Residence", "Kenwingston Square Garden", "Symphony Hills Mozart Type", "Kanvas Soho", "Centrus Soho", "Lakefront Residence", "Verdi Eco-Dominiums", "Aspen @ Garden Residence", "Tamarind Suites", "Cybersquare", "Sky Park", "Mutiara Ville" }));

        jComboBoxMaxPrice.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxMaxPrice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Max Price (RM)", "500", "1000", "1500", "2000", "2500", "3000", "3500", "4000", "5000" }));

        jComboBoxCurrentStatus.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxCurrentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Current Status", "Inactive", "Active" }));

        jComboBoxPriceSortingMethod.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBoxPriceSortingMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Price low to high", "Price high to low" }));

        jButtonSearch.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("rsz_1rsz_home-alt-512.png"))); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jCheckBoxSwimmingPool.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxSwimmingPool.setText("Swimming Pool");

        jCheckBoxTV.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxTV.setText("TV");

        jCheckBoxWifi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxWifi.setText("Wifi");

        jCheckBoxAirConditioner.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxAirConditioner.setText("Air-Conditioner");

        jCheckBoxFridge.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxFridge.setText("Fridge");

        jCheckBoxWaterHeater.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxWaterHeater.setText("Water Heater");

        jCheckBoxWashingMachine.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxWashingMachine.setText("Washing Machine");

        jCheckBoxGymRoom.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxGymRoom.setText("Gym Room");

        jCheckBoxBalcony.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxBalcony.setText("Balcony");

        jTablePropertyListing.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTablePropertyListing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTablePropertyListing);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Insert Property ID To Get Property Details:");

        jTextFieldPropertyID.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextFieldPropertyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPropertyIDActionPerformed(evt);
            }
        });

        jButtonGetPropertyDetail.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonGetPropertyDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("rsz_1rsz_home-alt-512.png"))); // NOI18N
        jButtonGetPropertyDetail.setText("Get");
        jButtonGetPropertyDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetPropertyDetailActionPerformed(evt);
            }
        });

        jButton14.setText("Add property");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBoxAirConditioner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxWifi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxTV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxSwimmingPool)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxFridge))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBoxWaterHeater)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxGymRoom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxBalcony)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxWashingMachine)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldAddress))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jComboBoxPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxPriceSortingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxCurrentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextFieldPropertyID, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGetPropertyDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(jButton14)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPriceSortingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCurrentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxSwimmingPool, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBoxAirConditioner)
                                .addComponent(jCheckBoxWifi)
                                .addComponent(jCheckBoxTV)
                                .addComponent(jCheckBoxFridge)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxWaterHeater)
                            .addComponent(jCheckBoxGymRoom)
                            .addComponent(jCheckBoxBalcony)
                            .addComponent(jCheckBoxWashingMachine)))
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPropertyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGetPropertyDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Profile.addTab("Property Manager", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Profile)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Profile, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        JFramePropertyOwnerAddProperty r = new JFramePropertyOwnerAddProperty();
        r.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButtonGetPropertyDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetPropertyDetailActionPerformed
        int propertyID = 0;
        boolean caught = false;
        Property foundProperty = null;
        PropertyManager newManager = PropertyManager.getInstance();

        if(jTextFieldPropertyID.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Please insert the Property ID");
        }
        else {
            try {
                caught = false;
                propertyID = Integer.parseInt(jTextFieldPropertyID.getText().trim());
            } catch (NumberFormatException e) {
                caught = true;
                JOptionPane.showMessageDialog(null, "Please insert numerical value in required text field");
            }
            if (caught == false) {
                foundProperty = newManager.findProperty(propertyID);
                if (foundProperty != null) {
                    new JFrameGetPropertyDetail(foundProperty).setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Property not found!");
                }

            }
        }
    }//GEN-LAST:event_jButtonGetPropertyDetailActionPerformed

    private void jTextFieldPropertyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPropertyIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPropertyIDActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        int propertyID = -1;
        String propertyType = "-1";
        double minPrice = -1;
        double maxPrice = -1;
        int uploader_userID = -1;
        ArrayList<String> facilities = new ArrayList<>();
        int currentStatus = -1;
        String projectName = "-1";
        int priceSortingMethod = jComboBoxPriceSortingMethod.getSelectedIndex();
        String address = "-1";
        if (!jTextFieldAddress.getText().isBlank()) {
            address = jTextFieldAddress.getText().trim();
        }
        if (jComboBoxPropertyType.getSelectedIndex() != 0) {
            propertyType = jComboBoxPropertyType.getSelectedItem().toString();
        }
        if (jComboBoxMinPrice.getSelectedIndex() != 0) {
            minPrice = Double.parseDouble(jComboBoxMinPrice.getSelectedItem().toString());
        }
        if (jComboBoxMaxPrice.getSelectedIndex() != 0) {
            maxPrice = Double.parseDouble(jComboBoxMaxPrice.getSelectedItem().toString());
        }
        if (jComboBoxCurrentStatus.getSelectedIndex() != 0) {
            currentStatus = jComboBoxCurrentStatus.getSelectedIndex() - 1;
        }
        if (jComboBoxProjectName.getSelectedIndex() != 0) {
            projectName = jComboBoxProjectName.getSelectedItem().toString();
        }
        ArrayList<JCheckBox> checkBoxes = new ArrayList<>();
        checkBoxes.add(jCheckBoxAirConditioner);
        checkBoxes.add(jCheckBoxBalcony);
        checkBoxes.add(jCheckBoxFridge);
        checkBoxes.add(jCheckBoxGymRoom);
        checkBoxes.add(jCheckBoxSwimmingPool);
        checkBoxes.add(jCheckBoxTV);
        checkBoxes.add(jCheckBoxWashingMachine);
        checkBoxes.add(jCheckBoxWaterHeater);
        checkBoxes.add(jCheckBoxWifi);
        for (int i = 0; i < checkBoxes.size(); i++) {
            if (checkBoxes.get(i).isSelected()) {
                facilities.add(checkBoxes.get(i).getText());
            }
        }
        ArrayList<Property> propertyList = new ArrayList<>();
        PropertyManager newManager = PropertyManager.getInstance();
        propertyList = newManager.searchProperty(propertyID, propertyType, minPrice, maxPrice,
            uploader_userID, facilities, currentStatus, projectName,
            priceSortingMethod, address);
        propertyTableSearchResult(jTablePropertyListing, propertyList);
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jComboBoxPropertyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPropertyTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPropertyTypeActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        JFrameUserEditRemove r = new JFrameUserEditRemove(admin);
        r.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        JFrameUserAdd r = new JFrameUserAdd(admin);
        r.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        JFrameUserViewer r = new JFrameUserViewer(admin);
        r.setVisible(true);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        userTableUpdate(jTable1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFrameRegistrationApproveDeny r = new JFrameRegistrationApproveDeny(admin);
        r.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrameModifyRegistrationForm r = new JFrameModifyRegistrationForm(admin);
        r.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.registrationTableUpdate(jTableRegistration);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JFrameVisitorPanel r = new JFrameVisitorPanel();
        r.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int userID = admin.getUserID();
        String userID_field = Integer.toString(userID);
        String userName_field = jTextField1.getText();
        String userPassword_field = jTextField2.getText();
        if (userPassword_field.equals("")){
            System.out.println("User password empty");
            userPassword_field = admin.getUserPassword();
        }
        String userRealName_field = jTextField3.getText();
        String userContact_field = jTextField4.getText();
        String userRole = jTextField5.getText();

        // int modifyUser(int userID, String userName, String userPassword, String userRealName, String userContact, String accountType)
        int returnCode = admin.modifyUser(userID_field, userName_field, userPassword_field, userRealName_field, userContact_field, userRole);

        if (returnCode == 0){
            JOptionPane.showMessageDialog(null, "Profile updated");
        }
        else if (returnCode == -1){
            JOptionPane.showMessageDialog(null, "User not found(what)", "Alert", JOptionPane.WARNING_MESSAGE);
        }

        else if (returnCode == -2){
            JOptionPane.showMessageDialog(null, "Empty username or password(what)", "Alert", JOptionPane.WARNING_MESSAGE);
        }

        else if (returnCode == -3){
            JOptionPane.showMessageDialog(null, "Invalid role(what)", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void userTableUpdate(JTable table){
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);
        
        ArrayList<User> userList = admin.getUserList();
        
        for (User user : userList){
            int userID = user.getUserID();
            String userName = user.getUserName();
            String userPassword = user.getUserPassword();
            String userRealName = user.getUserRealName();
            String userContact = user.getUserContact();
            String userRole = user.getUserRole();
            
            Object[] row = { userID, userName, userPassword, userRealName, userContact, userRole };
            
            tableModel.addRow(row);
        }
    }
    
    private void userTableInitialize(JTable table){
        String col[] = {"userID", "userName", "userPassword", "Real Name", "Contact info", "Role"};
        DefaultTableModel tableModel = new DefaultTableModel(0, col.length);
        tableModel.setColumnIdentifiers(col);
        table.setModel(tableModel);
        
        ArrayList<User> userList = admin.getUserList();
        
        for (User user : userList){
            int userID = user.getUserID();
            String userName = user.getUserName();
            String userPassword = user.getUserPassword();
            String userRealName = user.getUserRealName();
            String userContact = user.getUserContact();
            String userRole = user.getUserRole();
            
            Object[] row = { userID, userName, userPassword, userRealName, userContact, userRole };
            
            tableModel.addRow(row);
        }
    }
    
    private void registrationTableInitialize(JTable table){
        String col[] = {"userID", "userName", "userPassword", "Real Name", "Contact info", "Role"};
        DefaultTableModel tableModel = new DefaultTableModel(0, col.length);
        tableModel.setColumnIdentifiers(col);
        table.setModel(tableModel);
        
        ArrayList<User> registrationList = admin.getRegistrationList();

        for (User user : registrationList){
            int userID = user.getUserID();
            String userName = user.getUserName();
            String userPassword = user.getUserPassword();
            String userRealName = user.getUserRealName();
            String userContact = user.getUserContact();
            String userRole = user.getAccountType();
            
            Object[] row = { userID, userName, userPassword, userRealName, userContact, userRole };
            
            
            
            tableModel.addRow(row);
        }
    }
    
    private void registrationTableUpdate(JTable table){
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);
        
        ArrayList<User> registrationList = admin.getRegistrationList();

        for (User user : registrationList){
            int userID = user.getUserID();
            String userName = user.getUserName();
            String userPassword = user.getUserPassword();
            String userRealName = user.getUserRealName();
            String userContact = user.getUserContact();
            String userRole = user.getAccountType();
            
            Object[] row = { userID, userName, userPassword, userRealName, userContact, userRole };
            
            
            
            tableModel.addRow(row);
        }
    }
   private void clearPropertyTable(JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);
    }
    private void propertyTableSearchResult(JTable table, ArrayList<Property> propertyList) {
        clearPropertyTable(table);
        String col[] = {"Property ID", "Property Type", "Property Price", "Size (sqrt)", "Project Name", 
                        "Current Status", "Unit No", "Street", "Garden", "Postcode"};
        
        DefaultTableModel tableModel = new DefaultTableModel(0, col.length);
        tableModel.setColumnIdentifiers(col);
        table.setModel(tableModel);
        table.setEnabled(false);
        for (Property row : propertyList) {
            int propertyID = row.getPropertyID();
            String propertyType = row.getPropertyType();
            double propertyPrice = row.getPropertyPrice();
            double propertySize = row.getPropertySize();
            String projectName = row.getProjectName();
            // Property current status
            int currentStatus = row.getCurrentStatus();
            String statusString;
            if (currentStatus == 0) {
                statusString = "Inactive";
            }
            else {
                statusString = "Active";
            }
            // address
            ArrayList<String> address = row.getAddress();
            
            Object [] data = {propertyID, propertyType, propertyPrice, propertySize, projectName, 
                statusString, address.get(0), address.get(1), address.get(2), address.get(3)};
            tableModel.addRow(data);
        }
    }
    private void propertyTableInitialize(JTable table) {
        clearPropertyTable(table);
        String col[] = {"Property ID", "Property Type", "Property Price", "Size (sqrt)", "Project Name", 
                        "Current Status", "Unit No", "Street", "Garden", "Postcode"};
        
        DefaultTableModel tableModel = new DefaultTableModel(0, col.length);
        tableModel.setColumnIdentifiers(col);
        table.setModel(tableModel);
        table.setEnabled(false);
        
        PropertyManager propertyManager = PropertyManager.getInstance();
        ArrayList<Property> propertyList = propertyManager.getPropertyList();
        
        for (Property row : propertyList) {
            int propertyID = row.getPropertyID();
            String propertyType = row.getPropertyType();
            double propertyPrice = row.getPropertyPrice();
            double propertySize = row.getPropertySize();
            String projectName = row.getProjectName();
            // Property current status
            int currentStatus = row.getCurrentStatus();
            String statusString;
            if (currentStatus == 0) {
                statusString = "Inactive";
            }
            else {
                statusString = "Active";
            }
            // address
            ArrayList<String> address = row.getAddress();
            
            Object [] data = {propertyID, propertyType, propertyPrice, propertySize, projectName, 
                statusString, address.get(0), address.get(1), address.get(2), address.get(3)};
            tableModel.addRow(data);
        }
        
    }
      
//    private void propertyTableUpdate(JTable table){
//        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
//        tableModel.setRowCount(0);
//        
//        ArrayList<Property> propertyList = admin.getPropertyList();
//        
//        for (Property row : propertyList){
//            int propertyID = row.getPropertyID();
//            String propertyType = row.getPropertyType();
//            double propertyPrice = row.getPropertyPrice();
//            String ownerName = row.getOwnerName(); 
//            int uploader_userID = row.getUploader_userID();
//            String grantID = row.getGrantID();
//            String projectName = row.getProjectName();
//            int currentStatus = row.getCurrentStatus();
//            
//            // -- address -------------------------------
//            ArrayList<String> address = row.getAddress();
//            StringBuilder test_address = new StringBuilder();
//            for (String addressPart : address){
//                test_address.append(addressPart);
//            }
//            
//            String actualAddress = test_address.toString();      
//            // ------------------------------------------
//            
//            Object [] data = {propertyID, propertyType, propertyPrice, ownerName, uploader_userID, grantID, projectName, currentStatus, actualAddress};
//            
//            tableModel.addRow(data);
//            
//        }
//    }
    
//    private void propertyTableInitialize(JTable table){
//        String col[] = { "propertyID", "Property Type", "Property Price", "Owner name", "Uploader ID", "Grant ID", "Project name", "Current status", "Address" };
////        
////        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
////        table = new JTable(tableModel);
//        DefaultTableModel tableModel = new DefaultTableModel(0, col.length);
//        tableModel.setColumnIdentifiers(col);
//        table.setModel(tableModel);
//        //tableModel.setRowCount(0);
//        ArrayList<Property> propertyList = admin.getPropertyList();
//        
//        for (Property row : propertyList){
//            int propertyID = row.getPropertyID();
//            String propertyType = row.getPropertyType();
//            double propertyPrice = row.getPropertyPrice();
//            String ownerName = row.getOwnerName(); 
//            int uploader_userID = row.getUploader_userID();
//            String grantID = row.getGrantID();
//            String projectName = row.getProjectName();
//            int currentStatus = row.getCurrentStatus();
//            
//            // -- address -------------------------------
//            ArrayList<String> address = row.getAddress();
//            StringBuilder test_address = new StringBuilder();
//            for (String addressPart : address){
//                test_address.append(addressPart);
//            }
//            
//            String actualAddress = test_address.toString();      
//            // ------------------------------------------
//            
//            Object [] data = {propertyID, propertyType, propertyPrice, ownerName, uploader_userID, grantID, projectName, currentStatus, actualAddress};
//            
//            tableModel.addRow(data);
//            
//        }
//        
//    }
//    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Profile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonGetPropertyDetail;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JCheckBox jCheckBoxAirConditioner;
    private javax.swing.JCheckBox jCheckBoxBalcony;
    private javax.swing.JCheckBox jCheckBoxFridge;
    private javax.swing.JCheckBox jCheckBoxGymRoom;
    private javax.swing.JCheckBox jCheckBoxSwimmingPool;
    private javax.swing.JCheckBox jCheckBoxTV;
    private javax.swing.JCheckBox jCheckBoxWashingMachine;
    private javax.swing.JCheckBox jCheckBoxWaterHeater;
    private javax.swing.JCheckBox jCheckBoxWifi;
    private javax.swing.JComboBox<String> jComboBoxCurrentStatus;
    private javax.swing.JComboBox<String> jComboBoxMaxPrice;
    private javax.swing.JComboBox<String> jComboBoxMinPrice;
    private javax.swing.JComboBox<String> jComboBoxPriceSortingMethod;
    private javax.swing.JComboBox<String> jComboBoxProjectName;
    private javax.swing.JComboBox<String> jComboBoxPropertyType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelProfileTab;
    private javax.swing.JPanel jPanelRegistrationManagerTab;
    private javax.swing.JPanel jPanelUserManagerTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTablePropertyListing;
    private javax.swing.JTable jTableRegistration;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldPropertyID;
    // End of variables declaration//GEN-END:variables
}
