/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xavier
 */
public class JFramePropertyAgentHomepage extends javax.swing.JFrame {

    /**
     * Creates new form PropertyAgentHomePage
     */
    private PropertyAgent propertyAgent;
    public JFramePropertyAgentHomepage() {
        initComponents();
        propertyTableInitialize(propertyListing);
        this.setLocationRelativeTo(null);      
        this.setVisible(true);
        
    }
    
    public JFramePropertyAgentHomepage(PropertyAgent propertyAgent1) {
        propertyAgent = propertyAgent1;
        initComponents();
        
        propertyTableInitialize(propertyListing);
        this.setLocationRelativeTo(null);        
        this.setVisible(true);
        
    }
    // check either the input is integer or not
    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SearchPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        searchBox = new javax.swing.JTextField();
        propertyTypeField = new javax.swing.JComboBox<>();
        propertyStatusField = new javax.swing.JComboBox<>();
        propertyPriceField = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        projectNameField = new javax.swing.JComboBox<>();
        facility1 = new javax.swing.JCheckBox();
        facility6 = new javax.swing.JCheckBox();
        facility2 = new javax.swing.JCheckBox();
        facility7 = new javax.swing.JCheckBox();
        facility3 = new javax.swing.JCheckBox();
        facility8 = new javax.swing.JCheckBox();
        facility4 = new javax.swing.JCheckBox();
        facility9 = new javax.swing.JCheckBox();
        facility5 = new javax.swing.JCheckBox();
        sortingMethod = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        propertyListing = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        propertyIDtoView = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Property Agent Home Page");
        setMaximumSize(new java.awt.Dimension(5000, 5000));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Homepage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Property");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add Property");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("propertyAgentHome.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("editProfile.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("viewProperty.png"))); // NOI18N

        jButton7.setText("Edit Profile");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("editProperty.jpg"))); // NOI18N

        jButton8.setText("Edit Property");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("addproperty1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("Clogo.png"))); // NOI18N

        SearchPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Search:");

        searchBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });

        propertyTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Property Type", "Bungalow", "Semi-D", "Terrace/Link", "Townhouse", "Penthouse", "Condominium", "Duplex/Studio", "Apartment/Flat", "SoHo/SoVo/SoFo", "Mixed Development" }));
        propertyTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyTypeFieldActionPerformed(evt);
            }
        });

        propertyStatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Inactive", "Active" }));
        propertyStatusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyStatusFieldActionPerformed(evt);
            }
        });

        propertyPriceField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pricing (per month)", "RM200--", "RM200-300", "RM300-400", "RM400-500", "RM500-1000", "RM1000-1500", "RM1500-2000", "RM2000++" }));

        searchButton.setText("Apply Filter");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        projectNameField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Project/Area", "Cyberia", "Third Avenue", "Solstice", "Eclipse Residence", "Cristal Serin Residence", "Kenwingston Square Garden", "Symphony Hills Mozart Type", "Kanvas Soho", "Centrus Soho", "Lakefront Residence", "Verdi Eco-Dominiums", "Aspen @ Garden Residence", "Tamarind Suites", "Cybersquare", "Sky Park", "Mutiara Ville" }));
        projectNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectNameFieldActionPerformed(evt);
            }
        });

        facility1.setText("Air-Conditioner");

        facility6.setText("Water Heater");

        facility2.setText("Wifi");

        facility7.setText("Gym Room");

        facility3.setText("TV");
        facility3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facility3ActionPerformed(evt);
            }
        });

        facility8.setText("Balcony");

        facility4.setText("Swimming Pool");

        facility9.setText("Washing Machine");
        facility9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facility9ActionPerformed(evt);
            }
        });

        facility5.setText("Fridge");

        sortingMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Price low to high", "Price high to low" }));
        sortingMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortingMethodActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Sorting Method:");

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facility1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facility6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facility2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facility7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facility3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SearchPanelLayout.createSequentialGroup()
                                .addComponent(facility8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facility4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facility9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SearchPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sortingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                                .addComponent(facility5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(propertyStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertyTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(propertyPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(projectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(propertyTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(propertyPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(projectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(7, 7, 7)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addComponent(facility3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(facility8)
                            .addComponent(facility7)
                            .addComponent(facility6)
                            .addComponent(facility9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sortingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facility1)
                            .addComponent(facility2)
                            .addComponent(facility4)
                            .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(facility5)
                                .addComponent(propertyStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Cyberia Property Listing (Property Agent Interface)");

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        propertyListing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(propertyListing);

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel9.setText("Enter the property to view details:");

        jButton4.setText("View Property Details");
        jButton4.setMaximumSize(new java.awt.Dimension(135, 20));
        jButton4.setMinimumSize(new java.awt.Dimension(135, 20));
        jButton4.setPreferredSize(new java.awt.Dimension(135, 20));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(propertyIDtoView, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertyIDtoView, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void propertyTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propertyTypeFieldActionPerformed

    private void projectNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectNameFieldActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFramePropertyAgentViewProfile a = new JFramePropertyAgentViewProfile(propertyAgent);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        JFramePropertyAgentAddProperty a = new JFramePropertyAgentAddProperty(propertyAgent);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void facility3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facility3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facility3ActionPerformed

    private void facility9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facility9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facility9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // view property button
        this.dispose();
        JFramePropertyAgentViewProperty a = new JFramePropertyAgentViewProperty(propertyAgent);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        // edit property button
        this.dispose();
        JFramePropertyAgentEditProperty a = new JFramePropertyAgentEditProperty(propertyAgent);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // view property details button
        PropertyManager propertylist = PropertyManager.getInstance();
        // check if the field is empty or not integer
        if(propertyIDtoView.getText().equals("") || !isInteger(propertyIDtoView.getText()) ){
            // display error message
            JOptionPane.showMessageDialog(null,"Invalid Property ID!");        
        }
        else{     
            // get propertyID and further check
            int viewPropertyID = Integer.parseInt(propertyIDtoView.getText());
            // this function will return null if the propertyID is not under the property agent
            Property propertyToView = propertylist.findProperty(viewPropertyID);
            // display error
            if(propertyToView == null){
                JOptionPane.showMessageDialog(null,"Property is not in the system!");
            }
            // call frame of editing property
            else{
                this.dispose();
                JFramePropertyAgentHomepageViewDetails a = new JFramePropertyAgentHomepageViewDetails(propertyAgent,propertyToView);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void propertyStatusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyStatusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propertyStatusFieldActionPerformed

    private void sortingMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortingMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortingMethodActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        // 
        int propertyID = -1;
        String propertyType = "-1";
        double minPrice = -1;
        double maxPrice = -1;
        int uploader_userID = -1;
        ArrayList<String> facilities = new ArrayList<>();
        int currentStatus = -1;
        String projectName = "-1";
        int priceSortingMethod = sortingMethod.getSelectedIndex();
        String address = "-1";
        if (!searchBox.getText().isBlank()) {
            address = searchBox.getText().trim();
        }
        if (propertyTypeField.getSelectedIndex() != 0) {
            propertyType = propertyTypeField.getSelectedItem().toString();
        }
        if (propertyPriceField.getSelectedIndex() != 0) {
            if(propertyPriceField.getSelectedIndex() == 1){
                maxPrice = 200;
            }
            else if(propertyPriceField.getSelectedIndex() == 2){
                minPrice = 200;
                maxPrice = 300;
            }
            else if(propertyPriceField.getSelectedIndex() == 3){
                minPrice = 300;
                maxPrice = 400;
            }
            else if(propertyPriceField.getSelectedIndex() == 4){
                minPrice = 400;
                maxPrice = 500;
            }
            else if(propertyPriceField.getSelectedIndex() == 5){
                minPrice = 500;
                maxPrice = 1000;
            }
            else if(propertyPriceField.getSelectedIndex() == 6){
                minPrice = 1000;
                maxPrice = 1500;
            }
            else if(propertyPriceField.getSelectedIndex() == 7){
                minPrice = 1500;
                maxPrice = 2000;
            }
            else if(propertyPriceField.getSelectedIndex() == 8){
                minPrice = 2000;
            }
        }
        if (propertyStatusField.getSelectedIndex() != 0) {
            currentStatus = propertyStatusField.getSelectedIndex() - 1;
        }
        if (projectNameField.getSelectedIndex() != 0) {
            projectName = projectNameField.getSelectedItem().toString();
        }
        // facilities
        JCheckBox[] checkboxes = new JCheckBox[9];
        checkboxes[0] = facility1;
        checkboxes[1] = facility2;
        checkboxes[2] = facility3;
        checkboxes[3] = facility4;
        checkboxes[4] = facility5;
        checkboxes[5] = facility6;
        checkboxes[6] = facility7;
        checkboxes[7] = facility8;
        checkboxes[8] = facility9;
        for (int i = 0; i < checkboxes.length; i++) {
            if (checkboxes[i].isSelected()) {
                facilities.add(checkboxes[i].getText());
            }
        }
        ArrayList<Property> propertyList = new ArrayList<>();
        PropertyManager newManager = PropertyManager.getInstance();
        propertyList = newManager.searchProperty(propertyID, propertyType, minPrice, maxPrice,
                                    uploader_userID, facilities, currentStatus, projectName,
                                    priceSortingMethod, address);
        propertyTableSearchResult(propertyListing, propertyList);
    }//GEN-LAST:event_searchButtonActionPerformed

    
    private void clearPropertyTable(JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);
    }
    private void propertyTableSearchResult(JTable table, ArrayList<Property> propertyList) {
        clearPropertyTable(table);
        String col[] = { "ID", "Property Type", "Property Price","Property Size", "Project Name", "Number Of Rooms", "Number Of Bathooms", "Current status", "Address", "Facilities" }; 
        
        DefaultTableModel tableModel = new DefaultTableModel(0, col.length);
        tableModel.setColumnIdentifiers(col);
        table.setModel(tableModel);
        table.setEnabled(false);
        for (Property row : propertyList) {
            int propertyID = row.getPropertyID();
            String propertyType = row.getPropertyType();
            double propertyPrice = row.getPropertyPrice();
            double propertySize = row.getPropertySize();
            String projectName = row.getProjectName();
            // Property current status
            int numOfRooms = row.getNumRoom();
            int numOfBathrooms = row.getNumBathroom();
            int currentStatus = row.getCurrentStatus();
            String status = "Active";
            if (currentStatus == 0) {
                status = "Inactive";
            }
            // address
            String address = row.getAddress().get(1);
            ArrayList<String> facilities = row.getFacilities();
                StringBuilder test_facilities = new StringBuilder();
                for (String facilitiesPart : facilities){
                    test_facilities.append(facilitiesPart);
                    test_facilities.append(",");
                }

            String actualFacilities = test_facilities.toString(); 
            
            Object [] data = {propertyID, propertyType, propertyPrice, propertySize, projectName, numOfRooms,numOfBathrooms,
                status,address,actualFacilities };
            tableModel.addRow(data);
        }
    }
     private void propertyTableInitialize(JTable table){
        String col[] = { "ID", "Property Type", "Property Price","Property Size", "Project Name", "Number Of Rooms", "Number Of Bathooms", "Current status", "Address", "Facilities" }; 
        //  DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        //  table = new JTable(tableModel);
        DefaultTableModel tableModel = new DefaultTableModel(0, col.length);
        tableModel.setColumnIdentifiers(col);
        table.setModel(tableModel);
        table.getColumnModel().getColumn(0).setPreferredWidth(10);
        //tableModel.setRowCount(0);
        PropertyManager propertylist = PropertyManager.getInstance();
        ArrayList<Property> propertyList = propertylist.getPropertyList();
        Collections.reverse(propertyList);
        for (Property row : propertyList){
                int propertyID = row.getPropertyID();
                String propertyType = row.getPropertyType();
                double propertyPrice = row.getPropertyPrice();
                String propertySize = String.valueOf(row.getPropertySize());
                String projectName = row.getProjectName();
                String numberOfRoom = String.valueOf(row.getNumRoom());
                String numberOfBathoom = String.valueOf(row.getNumBathroom());
                
                String currentStatus = "Active";
                if(row.getCurrentStatus() == 0)
                     currentStatus = "Inactive";

                // -- address -------------------------------
                String address = row.getAddress().get(1);
                ArrayList<String> facilities = row.getFacilities();
                StringBuilder test_facilities = new StringBuilder();
                for (String facilitiesPart : facilities){
                    test_facilities.append(facilitiesPart);
                    test_facilities.append(",");
                }

                String actualFacilities = test_facilities.toString();      
                // ------------------------------------------

                Object [] data = {propertyID, propertyType, propertyPrice, propertySize,projectName, numberOfRoom, numberOfBathoom, currentStatus, address,actualFacilities};

                tableModel.addRow(data);     
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePropertyAgentHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePropertyAgentHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePropertyAgentHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePropertyAgentHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePropertyAgentHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JCheckBox facility1;
    private javax.swing.JCheckBox facility2;
    private javax.swing.JCheckBox facility3;
    private javax.swing.JCheckBox facility4;
    private javax.swing.JCheckBox facility5;
    private javax.swing.JCheckBox facility6;
    private javax.swing.JCheckBox facility7;
    private javax.swing.JCheckBox facility8;
    private javax.swing.JCheckBox facility9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> projectNameField;
    private javax.swing.JTextField propertyIDtoView;
    private javax.swing.JTable propertyListing;
    private javax.swing.JComboBox<String> propertyPriceField;
    private javax.swing.JComboBox<String> propertyStatusField;
    private javax.swing.JComboBox<String> propertyTypeField;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> sortingMethod;
    // End of variables declaration//GEN-END:variables
}
