/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 

import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class JFrameEditPropertyDetail extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEditPropertyDetail
     */
    public JFrameEditPropertyDetail() {
        initComponents();
    }
    
    Property property;
    
    public JFrameEditPropertyDetail(Property property) {
        this.property = property;
        initComponents();
        this.setLocationRelativeTo(null);
        propertyDetailInitialize();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCurrentStatus = new javax.swing.JComboBox<>();
        jComboBoxProjectName = new javax.swing.JComboBox<>();
        jComboBoxPropertyType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPropertyPrice = new javax.swing.JTextField();
        jTextFieldPropertyID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAddress2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAddress3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldAddress4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldNumBathroom = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldNumRoom = new javax.swing.JTextField();
        jTextFieldPropertySize = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldGrantID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldOwnerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAddress1 = new javax.swing.JTextField();
        jCheckBoxAirConditioner = new javax.swing.JCheckBox();
        jCheckBoxWifi = new javax.swing.JCheckBox();
        jCheckBoxWaterHeater = new javax.swing.JCheckBox();
        jCheckBoxGymRoom = new javax.swing.JCheckBox();
        jCheckBoxTV = new javax.swing.JCheckBox();
        jCheckBoxSwimmingPool = new javax.swing.JCheckBox();
        jCheckBoxBalcony = new javax.swing.JCheckBox();
        jCheckBoxWashingMachine = new javax.swing.JCheckBox();
        jCheckBoxFridge = new javax.swing.JCheckBox();
        jButtonSaveChanges = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldContactInfo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Property Detail");

        jComboBoxCurrentStatus.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBoxCurrentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactive", "Active" }));
        jComboBoxCurrentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCurrentStatusActionPerformed(evt);
            }
        });

        jComboBoxProjectName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBoxProjectName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cyberia", "Third Avenue", "Solstice", "Eclipse Residence", "Cristal Serin Residence", "Kenwingston Square Garden", "Symphony Hills Mozart Type", "Kanvas Soho", "Centrus Soho", "Lakefront Residence", "Verdi Eco-Dominiums", "Aspen @ Garden Residence", "Tamarind Suites", "Cybersquare", "Sky Park", "Mutiara Ville" }));
        jComboBoxProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProjectNameActionPerformed(evt);
            }
        });

        jComboBoxPropertyType.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBoxPropertyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bungalow", "Semi-D", "Terrace/Link", "Townhouse", "Penthouse", "Condominium", "Duplex/Studio", "Apartment/Flat", "SoHo/SoVo/SoFo", "Mixed Development" }));
        jComboBoxPropertyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPropertyTypeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Rental Rate:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Owner Grant ID:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Owner Name:");

        jTextFieldPropertyPrice.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextFieldPropertyID.setEditable(false);
        jTextFieldPropertyID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Unit No:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Street:");

        jTextFieldAddress2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("Property Type:");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Garden:");

        jTextFieldAddress3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Postcode:");

        jTextFieldAddress4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Facilities:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Number Of Bathroom:");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Number Of Room:");

        jTextFieldNumBathroom.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setText("Size (sqrt):");

        jTextFieldNumRoom.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextFieldPropertySize.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Edit Property Detail");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Project Name:");

        jTextFieldGrantID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setText("Current Status:");

        jTextFieldOwnerName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Property ID:");

        jTextFieldAddress1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jCheckBoxAirConditioner.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxAirConditioner.setText("Air-Conditioner");

        jCheckBoxWifi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxWifi.setText("Wifi");

        jCheckBoxWaterHeater.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxWaterHeater.setText("Water Heater");

        jCheckBoxGymRoom.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxGymRoom.setText("Gym Room");

        jCheckBoxTV.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxTV.setText("TV");

        jCheckBoxSwimmingPool.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxSwimmingPool.setText("Swimming Pool");

        jCheckBoxBalcony.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxBalcony.setText("Balcony");

        jCheckBoxWashingMachine.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxWashingMachine.setText("Washing Machine");

        jCheckBoxFridge.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBoxFridge.setText("Fridge");

        jButtonSaveChanges.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonSaveChanges.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOAD_Assignment/save.png"))); // NOI18N
        jButtonSaveChanges.setText("Save Changes");
        jButtonSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveChangesActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setText("Contact Info:");

        jTextFieldContactInfo.setEditable(false);
        jTextFieldContactInfo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldNumBathroom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldGrantID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPropertyPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jTextFieldOwnerName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPropertyID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCurrentStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxProjectName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxWaterHeater)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxGymRoom))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxAirConditioner)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxWifi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxFridge))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxTV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxBalcony)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxSwimmingPool))
                                    .addComponent(jCheckBoxWashingMachine))
                                .addGap(0, 42, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jTextFieldPropertySize, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxPropertyType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldAddress2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(jTextFieldAddress3)
                            .addComponent(jTextFieldAddress4)
                            .addComponent(jTextFieldAddress1)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldContactInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSaveChanges)
                        .addGap(50, 50, 50)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPropertyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPropertyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAddress4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPropertySize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGrantID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxAirConditioner)
                            .addComponent(jCheckBoxWifi)
                            .addComponent(jCheckBoxFridge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxWaterHeater)
                    .addComponent(jCheckBoxGymRoom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumBathroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxTV)
                    .addComponent(jCheckBoxBalcony)
                    .addComponent(jCheckBoxSwimmingPool))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxWashingMachine)
                    .addComponent(jComboBoxCurrentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveChangesActionPerformed

        // Check values are inserted by the user or not
        if (jTextFieldAddress1.getText().isBlank() || jTextFieldAddress2.getText().isBlank() ||
            jTextFieldAddress3.getText().isBlank() || jTextFieldAddress4.getText().isBlank() ||
            jTextFieldGrantID.getText().isBlank() || jTextFieldNumBathroom.getText().isBlank() ||
            jTextFieldNumRoom.getText().isBlank() || jTextFieldOwnerName.getText().isBlank() ||
            jTextFieldPropertyPrice.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Please insert all the text field!");
        }

        else {
            // Check try catch
            boolean caught = false;
            // Parameters needed
            int propertyID = property.getPropertyID();
            double propertyPrice = 0;
            double propertySize = 0;
            int numBathroom = 0;
            int numRoom = 0;
            String propertyType;
            String ownerName;
            int uploader_userID;
            String grantID;
            String projectName;
            int currentStatus;
            ArrayList<String> address;
            ArrayList<String> facilities;

            // Check numerical value or not
            try {
                caught = false;
                propertyPrice = Double.parseDouble(jTextFieldPropertyPrice.getText().trim());
                propertySize = Double.parseDouble(jTextFieldPropertySize.getText().trim());
                numBathroom = Integer.parseInt(jTextFieldNumBathroom.getText().trim());
                numRoom = Integer.parseInt(jTextFieldNumRoom.getText().trim());
            } catch (NumberFormatException e) {
                caught = true;
                JOptionPane.showMessageDialog(null, "Please insert numerical value in required text field");
            }
            // If numerical value
            if (caught == false) {
                propertyType = jComboBoxPropertyType.getSelectedItem().toString();
                ownerName = jTextFieldOwnerName.getText().trim();
                grantID = jTextFieldGrantID.getText().trim();
                projectName = jComboBoxProjectName.getSelectedItem().toString();
                currentStatus = jComboBoxCurrentStatus.getSelectedIndex();
                address = new ArrayList<>();
                address.add(jTextFieldAddress1.getText().trim());
                address.add(jTextFieldAddress2.getText().trim());
                address.add(jTextFieldAddress3.getText().trim());
                address.add(jTextFieldAddress4.getText().trim());
                facilities = new ArrayList<>();
                ArrayList<JCheckBox> checkBoxes = new ArrayList<>();
                checkBoxes.add(jCheckBoxAirConditioner);
                checkBoxes.add(jCheckBoxBalcony);
                checkBoxes.add(jCheckBoxFridge);
                checkBoxes.add(jCheckBoxGymRoom);
                checkBoxes.add(jCheckBoxSwimmingPool);
                checkBoxes.add(jCheckBoxTV);
                checkBoxes.add(jCheckBoxWashingMachine);
                checkBoxes.add(jCheckBoxWaterHeater);
                checkBoxes.add(jCheckBoxWifi);
                for (int i = 0; i < checkBoxes.size(); i++) {
                    if (checkBoxes.get(i).isSelected()) {
                        facilities.add(checkBoxes.get(i).getText());
                    }
                }
                PropertyManager manager = PropertyManager.getInstance();
                manager.modifyProperty(propertyID, propertyType, propertyPrice, propertySize,
                        ownerName, grantID, projectName, currentStatus, numBathroom, numRoom, 
                        address, facilities);
                JOptionPane.showMessageDialog(null, "Submitted!");
                this.dispose();
            }

        }
    }//GEN-LAST:event_jButtonSaveChangesActionPerformed

    private void jComboBoxProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProjectNameActionPerformed

    private void jComboBoxPropertyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPropertyTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPropertyTypeActionPerformed

    private void jComboBoxCurrentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCurrentStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCurrentStatusActionPerformed

    private void propertyDetailInitialize() {
        LoginIDManager loginManager = LoginIDManager.getInstance();
        User currentUser = loginManager.getUser(property.getUploader_userID());
        // Facilities
        ArrayList<String> facilities = property.getFacilities();
        if (facilities.contains("Air-Conditioner"))
            jCheckBoxAirConditioner.setSelected(true);
        if (facilities.contains("Balcony"))
            jCheckBoxBalcony.setSelected(true);
        if (facilities.contains("Fridge"))
            jCheckBoxFridge.setSelected(true);
        if (facilities.contains("Gym Room"))
            jCheckBoxGymRoom.setSelected(true);
        if (facilities.contains("Swimming Pool"))
            jCheckBoxSwimmingPool.setSelected(true);
        if (facilities.contains("TV"))
            jCheckBoxTV.setSelected(true);
        if (facilities.contains("Washing Machine"))
            jCheckBoxWashingMachine.setSelected(true);
        if (facilities.contains("Water Heater"))
            jCheckBoxWaterHeater.setSelected(true);
        if (facilities.contains("Wifi"))
            jCheckBoxWifi.setSelected(true);
            
            
        // Address
        ArrayList<String> addresses = property.getAddress();
        jTextFieldAddress1.setText(addresses.get(0));
        jTextFieldAddress2.setText(addresses.get(1));
        jTextFieldAddress3.setText(addresses.get(2));
        jTextFieldAddress4.setText(addresses.get(3));
        // Current Status
        int currentStatus = property.getCurrentStatus();
        if (currentStatus == 0)
            jComboBoxCurrentStatus.setSelectedIndex(0);
        else
            jComboBoxCurrentStatus.setSelectedIndex(1);
        // Contact info
        jTextFieldContactInfo.setText(currentUser.getUserContact());
        // Other information
        jTextFieldGrantID.setText(property.getGrantID());
        jTextFieldNumBathroom.setText(Integer.toString(property.getNumBathroom()));
        jTextFieldNumRoom.setText(Integer.toString(property.getNumRoom()));
        jTextFieldOwnerName.setText(property.getOwnerName());
        jTextFieldPropertyID.setText(Integer.toString(property.getPropertyID()));
        jTextFieldPropertyPrice.setText(Double.toString(property.getPropertyPrice()));
        jTextFieldPropertySize.setText(Double.toString(property.getPropertySize()));
        jComboBoxPropertyType.setSelectedItem(property.getPropertyType());
        jComboBoxProjectName.setSelectedItem(property.getProjectName());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEditPropertyDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEditPropertyDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEditPropertyDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEditPropertyDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEditPropertyDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveChanges;
    private javax.swing.JCheckBox jCheckBoxAirConditioner;
    private javax.swing.JCheckBox jCheckBoxBalcony;
    private javax.swing.JCheckBox jCheckBoxFridge;
    private javax.swing.JCheckBox jCheckBoxGymRoom;
    private javax.swing.JCheckBox jCheckBoxSwimmingPool;
    private javax.swing.JCheckBox jCheckBoxTV;
    private javax.swing.JCheckBox jCheckBoxWashingMachine;
    private javax.swing.JCheckBox jCheckBoxWaterHeater;
    private javax.swing.JCheckBox jCheckBoxWifi;
    private javax.swing.JComboBox<String> jComboBoxCurrentStatus;
    private javax.swing.JComboBox<String> jComboBoxProjectName;
    private javax.swing.JComboBox<String> jComboBoxPropertyType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldAddress1;
    private javax.swing.JTextField jTextFieldAddress2;
    private javax.swing.JTextField jTextFieldAddress3;
    private javax.swing.JTextField jTextFieldAddress4;
    private javax.swing.JTextField jTextFieldContactInfo;
    private javax.swing.JTextField jTextFieldGrantID;
    private javax.swing.JTextField jTextFieldNumBathroom;
    private javax.swing.JTextField jTextFieldNumRoom;
    private javax.swing.JTextField jTextFieldOwnerName;
    private javax.swing.JTextField jTextFieldPropertyID;
    private javax.swing.JTextField jTextFieldPropertyPrice;
    private javax.swing.JTextField jTextFieldPropertySize;
    // End of variables declaration//GEN-END:variables
}
